return {
    ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "bash-language-server",
        "black",
        "blade-formatter",
        "clangd",
        "codespell",
        "css-lsp",
        "debugpy",
        "delve",
        "docker-compose-language-service",
        "elixir-ls",
        "erlang-debugger",
        "erlang-ls",
        "goimports",
        "gopls",
        "html-lsp",
        "isort",
        "json-lsp",
        "kube-linter",
        "laravel-ls",
        "lemminx",
        "lua-language-server",
        "luau-lsp",
        "omnisharp",
        "php-cs-fixer",
        "phpactor",
        "phpcbf",
        "pint",
        "prettier",
        "prettierd",
        "rust-analyzer",
        "sqlls",
        "stylua",
        "tofu-ls",
        "typescript-language-server",
        "yaml-language-server",
        "golangci-lint"
    },

    ui = {
        icons = {
            package_installed = "✓",
            package_pending = "➜",
            package_uninstalled = "✗",
        },
    },
    log_level = vim.log.levels.DEBUG,
}
