return {
    {
        "nvim-treesitter/nvim-treesitter",
        build = ":TSUpdate",
        opts = {
            indent = {
                enable = true,
            },
            auto_install = true,
            highlight = {
                enable = true,
            },
            ensure_installed = {
                "vim",
                "lua",
                "vimdoc",
                "html",
                "css",
                "dockerfile",
                "php",
                "blade",
                "javascript",
                "typescript",
                "python",
                "c",
                "cpp",
                "rust",
                "go",
                "gosum",
                "gomod",
                "gowork",
                "json",
                "yaml",
                "markdown",
                "markdown_inline",
                "erlang",
                "elixir",
                "bash",
                "toml",
                "latex",
                "vue",
                "norg",
                "scss",
                "svelte",
                "tsx",
                "typst",
                "regex",
                "astro",
                "terraform",
                "hcl",
            },
        },
        config = function(_, opts)
            require("nvim-treesitter.configs").setup(opts)
        end,
    },
}
