require("nvchad.mappings")

local map = vim.keymap.set

map("n", ";", ":", { silent = true, desc = "CMD enter command mode" })
map("i", "jk", "<ESC>", { silent = true, desc = "ESC for insert mode" })
map("n", "<leader>bn", "<cmd> enew <CR>", { silent = true, desc = "buffer new" })
map("n", "<leader>to", "<cmd>tabnew<CR>", { silent = true, desc = "Open new tab" })
map("n", "<leader>tq", "<cmd>tabclose<CR>", { silent = true, desc = "Close current tab" })
map("n", "<leader>tn", "<cmd>tabn<CR>", { silent = true, desc = "Go to next tab" })
map("n", "<leader>tp", "<cmd>tabp<CR>", { silent = true, desc = "Go to previous tab" })
map("n", "<leader>tf", "<cmd>tabnew %<CR>", { silent = true, desc = "Open current buffer in new tab" })
map("n", "<C-p>", ":FloatermToggle<CR>", { silent = true, desc = "Terminal floaterm" })
map("n", "<C-b>", ":NvimTreeToggle<CR>", { silent = true, desc = "Toggle NvimTree" })
map("n", "gp", "<cmd>lua require('goto-preview').goto_preview_definition()<CR>", { noremap = true })
map("n", "<C-t>", function()
    require("menu").open("default")
end, {})
map("n", "<C-g", function()
    require("triforce").show_profile()
end, { desc = "tampilkan triforce statsnya" })
map("n", "<C-a>", ":Telescope<CR>", { noremap = true, silent = true })
map("n", "<leader>mm", ":messages<CR>", { desc = "Show Neovim Messages" })
map("n", "<Leader>qq", ":q<CR>", { noremap = true, silent = true, desc = "exit" })
map("n", "<Leader>qa", ":qa<CR>", { noremap = true, silent = true, desc = "exit for all" })
map("n", "<Leader>ll", ":Lazy<CR>", { noremap = true, silent = true, desc = "Buka Lazy.nvim" })
map("n", "<Leader>ls", ":Lazy sync<CR>", { noremap = true, silent = true, desc = "Buka Lazy.nvim sync" })
map("n", "<Leader>lm", ":Mason<CR>", { noremap = true, silent = true, desc = "Buka Mason.nvim" })
map("n", "<leader>d/", ":%s/\\s*\\/\\/.*$//e<CR>", { desc = "Hapus komentar // sampai akhir" })
map("n", "<leader>d#", ":%s/\\s*##.*$//e<CR>", { desc = "Hapus komentar ## sampai akhir" })
map("n", "<leader>d-", ":%s/\\s*--.*$//e<CR>", { desc = "Hapus komentar -- sampai akhir" })
map("n", "<leader>ca", ":%bd|e#|bd#<CR>", { desc = "Close all buffers except current" })
map("t", "<Esc>", [[<C-\><C-n>]], { noremap = true, silent = true, desc = "keluar dari mode terminal" })
map("n", "<A-j>", ":m .+1<CR>==", { desc = "Pindahkan baris ke bawah" })
map("n", "<A-k>", ":m .-2<CR>==", { desc = "Pindahkan baris ke atas" })
map("v", "<A-j>", ":m '>+1<CR>gv=gv", { desc = "Pindahkan seleksi ke bawah" })
map("v", "<A-k>", ":m '<-2<CR>gv=gv", { desc = "Pindahkan seleksi ke atas" })
