return {
    { require("plugins.nvim-treesitter") },
    { require("plugins.colorizer") },
    { require("plugins.jqx") },
    { require("plugins.conform") },
    { require("plugins.nvim-lspconfig") },
    { require("plugins.hlchunk-module") },
    { require("plugins.nvim-tree") },
    { require("plugins.mason") },
    { require("plugins.nvim-dap") },
    { require("plugins.nvim-dap-python") },
    { require("plugins.nvim-lint") },
    { require("plugins.volt") },
    { require("plugins.menu") },
    { require("plugins.timerly") },
    { require("plugins.floaterm") },
    { require("plugins.triforce") },
    { require("plugins.vim-wakatime") },
    { require("plugins.markview") },
    { require("plugins.todo-comments") },
    { require("plugins.trouble") },
    { require("plugins.nvim-cmp") },
    { require("plugins.git-blame") },
}
