return {
    { require("plugins.nvim-treesitter") },
    { require("plugins.colorizer") },
    { require("plugins.jqx") },
    { require("plugins.conform") },
    { require("plugins.nvim-lspconfig") },
    { require("plugins.nvim-tree") },
    { require("plugins.mason") },
    { require("plugins.nvim-dap") },
    { require("plugins.nvim-dap-python") },
    { require("plugins.nvim-lint") },
    { require("plugins.volt") },
    { require("plugins.menu") },
    { require("plugins.timerly") },
    { require("plugins.floaterm") },
    { require("plugins.triforce") },
    { require("plugins.vim-wakatime") },
    { require("plugins.markview") },
    { require("plugins.todo-comments") },
    { require("plugins.trouble") },
    { require("plugins.nvim-cmp") },
    { require("plugins.git-blame") },
    { require("plugins.snacks") },
    -- {
    --     {
    --         "folke/snacks.nvim",
    --         priority = 1000,
    --         lazy = false,
    --         -- @type snacks.Config
    --         opts = {
    --             bigfile = { enabled = true },
    --             dashboard = { enabled = true },
    --             explorer = { enabled = true },
    --             indent = { enabled = true },
    --             input = { enabled = true },
    --             picker = { enabled = true },
    --             notifier = { enabled = true },
    --             quickfile = { enabled = true },
    --             scope = { enabled = true },
    --             scroll = { enabled = true },
    --             statuscolumn = { enabled = true },
    --             words = { enabled = true },
    --         },
    --     },
    -- },
}
