return {
    {
        "folke/snacks.nvim",
        priority = 1000,
        lazy = false,
        opts = {
            lazygit = {},
            bigfile = { enabled = true },
            dashboard = { enabled = true },
            explorer = {
                preplace_netrw = true,
                trash = true,
            },
            indent = { enabled = true },
            input = { enabled = true },
            picker = {
                source = {
                    explorer = {},
                },
            },
            quickfile = { enabled = true },
            scope = { enabled = true },
            scroll = { enabled = true },
            statuscolumn = { enabled = true },
            words = { enabled = true },
            image = {
                formats = {
                    "png",
                    "jpg",
                    "jpeg",
                    "gif",
                    "bmp",
                    "webp",
                    "tiff",
                    "heic",
                    "avif",
                    "mp4",
                    "mov",
                    "avi",
                    "mkv",
                    "webm",
                    "pdf",
                    "icns",
                },
                force = false,
            },
            notifier = {
                timeout = 3000,
                width = { min = 40, max = 0.4 },
                height = { min = 1, max = 0.6 },
                margin = { top = 0, right = 1, bottom = 0 },
                padding = true,
                gap = 0,
                sort = { "level", "added" },

                level = vim.log.levels.TRACE,
                icons = {
                    error = " ",
                    warn = " ",
                    info = " ",
                    debug = " ",
                    trace = " ",
                },
                keep = function(notif)
                    return vim.fn.getcmdpos() > 0
                end,
                style = "compact",
                top_down = true,
                date_format = "%R",
                more_format = " ↓ %d lines ",
                refresh = 50,
            },
        },
    },
}
